experiencia/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'experiencia'  # define o namespace para o aplicativo

urlpatterns = [
    path('form',views.form,name='form'),
    path('gemonis/Smolder173',views.experiencia,name='perfil'),

]

experiencia_agStudio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('experiencia/',include('experiencia.urls'),name='experiencia'),
]

action/models.py
from django.db import models

# Create your models here.

experiencia/models.py
from django.db import models
from django.utils import timezone

class Question(models.Model):
    field = models.CharField(max_length=500)
    question =  models.CharField(max_length=500)
    createAt = models.DateTimeField(default=timezone.now)

class Answers(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=500)
    results = models.IntegerField(default=0,null=True)
    percentage = models.DecimalField(default=0, max_digits=8, decimal_places=2,null=True)
    createAt = models.DateTimeField(default=timezone.now)

experiencia/forms.py
from django import forms

class Question_forms(forms.Form):
    CHOICES_find_us = [
        ('Facebook', 'Facebook'),
        ('Instagram', 'Instagram'),
        ('Indicação', 'Indicação'),
        ('Outros', 'Outros')
    ]
    CHOICES_location = [
        ('Bem Localizado', 'Bem Localizado'),
        ('Difício acesso', 'Difício acesso'),
        ('Falta sinalização', 'Falta sinalização'),
        ('Outros', 'Outros')
    ]
    CHOICES_organizacao = [
        ('Bem organizado e limpo', 'Bem organizado e limpo'),
        ('Não estava organizado quando fui', 'Não estava organizado quando fui'),
        ('Achei o ambiente desorganizado e sujo', 'Achei o ambiente desorganizado e sujo'),
        ('Outros', 'Outros')
    ]
    CHOICES_espera = [
        ('Fui atendida bem rápido, não precisei esperar muito.', 'Fui atendida bem rápido, não precisei esperar muito.'),
        ('Infelizmente precisei aguardar por alguns minutos.', 'Infelizmente precisei aguardar por alguns minutos.'),
    ]
    
    CHOICES_atendimento = [
        ('Minhas dúvidas foram esclarecidas', 'Minhas dúvidas foram esclarecidas'),
        ('Fui orientada sobre todos os cuidados pós procedimento.', 'Fui orientada sobre todos os cuidados pós procedimento.'),
        ('Fiquei confortável e me senti segura durante o procedimento.', 'Fiquei confortável e me senti segura durante o procedimento.'),
        ('Outros', 'Outros')
    ]
    CHOICES_about_our_employees = [
        ('Muito boa! São simpáticas e trabalham super bem.', 'Muito boa! São simpáticas e trabalham super bem.'),
        ('Muitas conversas paralelas e não me senti confortável.', 'Muitas conversas paralelas e não me senti confortável.'),
    ]
    CHOICES_do_you_intend_to_return = [
        ('Com certeza!', 'Com certeza!'),
        ('Hum, acho que não.', 'Hum, acho que não.'),
        ('Assim que possível.', 'Assim que possível.'),
    ]

    how_you_find_us = forms.ChoiceField(
        label="Como você nos encontrou?",
        choices=CHOICES_find_us,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    about_our_location = forms.ChoiceField(
        label="Sobre nossa localização:",
        choices=CHOICES_location,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    About_organization_space = forms.ChoiceField(
        label="Sobre a organização do espaço:",
        choices=CHOICES_organizacao,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    waitin_time = forms.ChoiceField(
        label="Tempo de espera:",
        choices=CHOICES_espera,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    about_our_service = forms.ChoiceField(
        label="Sobre o atendimento:",
        choices=CHOICES_atendimento,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    about_our_employees = forms.ChoiceField(
        label="Como foi sua experiência com nossas funcionárias?",
        choices=CHOICES_about_our_employees,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )
    do_you_intend_to_return = forms.ChoiceField(
        label="Você pretende voltar?",
        choices=CHOICES_do_you_intend_to_return,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
    )

    # criticize_or_praise = models.CharField(max_length=500)
    # rate = models.IntegerField()

action/views.py
from django.shortcuts import render

# Create your views here.

experiencia/views.py
from django.shortcuts import render
from .forms import Question_forms
from functions.database import insert_answer_to_questionnaire
from django.contrib import messages
from .models import Answers,Question
import pandas as pd

# Create your views here.
def form(request):
    context = {} 
    context['form'] = Question_forms()
    if request.method == 'POST':
        iter_items = iter(request.POST.items())
        next(iter_items)  # pula o primeiro item
        answers = {i: (int(v) if i == 'rate' else v) for i, v in iter_items}
        rate_depara = {1:"Péssimo",2:"Ruim",3:"Regular",4:"Bom",5:"Ótimo"}
        answers['rate'] = rate_depara[answers['rate']]

        if not insert_answer_to_questionnaire(answers):
            messages.error(request,"Ops! Algo deu errado. Por favor, tente novamente mais tarde. Desculpe pelo inconveniente!")
        else:
            if answers['rate'] == "Péssimo":
                msg = "Agradecemos pelo seu feedback. Vamos trabalhar duro para melhorar."
            elif answers['rate'] == "Ruim":
                msg = "Muito obrigado pela sua avaliação. Seus comentários nos ajudam a crescer."
            elif answers['rate'] == "Regular":
                msg = "Obrigado por nos avaliar. Valorizamos sua opinião e continuaremos a melhorar."
            elif answers['rate'] == "Bom":
                msg = "Apreciamos sua avaliação positiva. Estamos felizes em saber que você teve uma boa experiência conosco."
            elif answers['rate'] == "Ótimo":
                msg = "Uau! Obrigado pela avaliação incrível. Seu feedback nos motiva a continuar oferecendo um serviço excepcional."
            messages.success(request,msg)

    return render(request,'questionario/index.html',context)

def experiencia(request):
    context = {}
    context['cards'] = []
    
    # get the all values to Answer and questio db and make a join with pandas
    df_answer = pd.DataFrame.from_records(Answers.objects.filter().all().values())
    df_question = pd.DataFrame.from_records(Question.objects.filter().all().values())

    df = pd.merge(df_question,df_answer,left_on='id', right_on='question_id', how='inner')

    # get all question to make a for 
    for index,question in enumerate([q['question'] for q in list(Question.objects.all().values('question'))]):
        results = {}
        filter_df = df[(df['question'])==question]
        new_df = filter_df[['answer','results','percentage']]
        new_df['percentage'] = new_df['percentage'].astype(float)
        dict_new_df = new_df.to_dict('records')
        results['question'] = question
        results['values'] = dict_new_df
        results['div_id_question'] = f'question-id-{index}'
        results['div_id_progress'] = f'progres-bar-id-{index}'
        results['index'] = index

        context['cards'].append(results)
    return render(request,'perfil/index.html',context)

templates/_alertas.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    
    {% block head%}
    {% endblock %}
    
    <!-- bootstrap -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} {% endblock %}</title>

</head>

    <body>
        
        <!-- content -->
        <main>
        
            {% block content %}
            {% endblock %}
        
        </main>
        
        <footer>
            <!-- Rodapé do site -->
        </footer>
    
    </body>

</html>

templates/perfil/index.html
{% load static %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- jquery -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     
      <!-- css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/perfil/styles.css' %}">
     
      <!-- js -->
      <script src='{% static "js/perfil/main.js" %}' language="JavaScript" type="text/javascript"></script>
     
      <!-- bootstrap -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      
      <!-- favicon -->
      <link href="{% static 'img/favicon/AG_LOGO.png' %}" rel="icon" sizes="32x32">
      
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>AG STUDIO | ANÁLISE</title>
   </head>
   <body style="background-color: #fbdbdb;">
      <!-- content -->
      <main>
         <div class="container">
            <div class="row justify-content-center mt-5">
               <div class="col-md-6">
                  <div class="image-container">
                     <img src="{% static 'img/favicon/AG_LOGO.png' %}" alt=""">
                        <div style="margin-bottom: 1rem;">
                           <button class="btn btn-primary" style="width: 100%;" onclick="copiarURL()">Copiar URL do formulário</button>
                           <div id="copy-done"  style="margin-top: 0.2rem; display: none;" class="card-header text-center">
                              <span class="copiado">Copiado</span>
                              <span class="icone">{% bs_icon 'check' size='2rem' %}</span>
                           </div>
                        </div>

                     {% for card in cards %}
                        <div style="margin-bottom: 0.5rem;" class="card">
                        <div class="card-header">
                           {{card.question}}
                        </div>
                        <div class="card-body">
                           {% for value in card.values %}
                              {{value.answer}}
                              <div class="percentage-value" style="display:none;">{{value.percentage}}</div>
                              <div class="progress">
                                 {% if value.percentage > 60 %}
                                    <!-- Condição 1 -->
                                    <div class="progress-bar" role="progressbar" style="width: {{value.percentage}}%; background-color: #04AA6D" aria-valuenow="{{value.percentage}}" aria-valuemin="0" aria-valuemax="100">{{value.results}}</div>
                                 {% elif value.percentage > 30 %}
                                    <!-- Condição 2 -->
                                    <div class="progress-bar" role="progressbar" style="width: {{value.percentage}}%; background-color: #2196F3" aria-valuenow="{{value.percentage}}" aria-valuemin="0" aria-valuemax="100">{{value.results}}</div>
                                 {% elif value.percentage > 10 %}
                                    <!-- Condição 3 -->
                                    <div class="progress-bar" role="progressbar" style="width: {{value.percentage}}%; background-color: #00bcd4" aria-valuenow="{{value.percentage}}" aria-valuemin="0" aria-valuemax="100">{{value.results}}</div>
                                 {% else %}
                                    <!-- Condição padrão -->
                                    <div class="progress-bar" role="progressbar" style="width: {{value.percentage}}%; background-color: #ff9800" aria-valuenow="{{value.percentage}}" aria-valuemin="0" aria-valuemax="100">{{value.results}}</div>
                                 {% endif %}
                              </div>
                           {% endfor %}
                        </div>
                        </div>
                     {% endfor %}
            </div>
         </div>
         </div>
      </main>
      <footer>
         <!-- Rodapé do site -->
      </footer>
   </body>
</html>
<script>
   function copiarURL() {
       var dominio = window.location.hostname;  // Obtém o domínio do URL atual
       var url = "http://" + dominio + "{% url 'experiencia:form' %}";  // Combina o domínio com a URL
       var inputElement = document.createElement("input");
       inputElement.setAttribute("value", url);
       document.body.appendChild(inputElement);
       inputElement.select();
       document.execCommand("copy");
       document.body.removeChild(inputElement);
       // Mostrar a div #copy-done
      var copyDoneDiv = document.getElementById("copy-done");
      copyDoneDiv.style.display = "block";
      // copyDoneDiv.style.opacity = "0";

      // Animar o aparecimento e desaparecimento da div
      $(copyDoneDiv).fadeIn(500, function() {
         setTimeout(function() {
            $(copyDoneDiv).fadeOut(500);
         }, 1000);
      });

   }
</script>

templates/questionario/index.html
{% load static %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- jquery -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     
      <!-- css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/questionario/styles.css' %}">
     
      <!-- js -->
      <script src='{% static "js/questionario/main.js" %}' language="JavaScript" type="text/javascript"></script>
     
      <!-- bootstrap -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      
      <!-- favicon -->
      <link href="{% static 'img/favicon/AG_LOGO.png' %}" rel="icon" sizes="32x32">
      
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>AG STUDIO | EXPERIENCIA</title>
   </head>
   <body style="background-color: #fbdbdb;">
      <!-- content -->
      <main>
         <div class="container">
            <div class="row justify-content-center mt-5">
               <div class="col-md-6">
                  <div class="image-container">
                     <img src="{% static 'img/favicon/AG_LOGO.png' %}" alt=""">
                  </div>
                  {% include "_alertas.html" %}
                  <div style="margin-bottom: 5rem;margin-top: 0.2rem;" class="card">
                     <form method="POST" action="{% url 'experiencia:form' %}">
                        {% csrf_token %}
                        <div style="padding: 0.5rem;margin-top: -1rem;" class="card">
                           <div  class="card-header text-center">
                              Avalie sua experiência conosco {% bs_icon 'arrow-through-heart-fill'  size='1rem' %}
                           </div>
                           {% for question in form %}
                                 <div  class="card card-question">
                                    <div class="card-header">{{question.label}} <strong>*</strong></div>
                                    <div>
                                       <div class="check-question">
                                          {% for choice in question %}
                                          <div class="form-check">
                                             {% render_field choice  %}
                                          </div>
                                          {% endfor %}
                                       </div>
                                    </div>
                                 </div>
                           {% endfor %}
                           <div  class="card card-question">
                              <div class="card-header">Sua nota para sua experiencia na AG studio:<strong>*</strong></div>
                              <div>
                                 <div class="check-question text-center">
                                    <div class="form-check">
                                       <div class="rate">
                                          <input type="radio" id="star5" name="rate" value="5" />
                                          <label for="star5" title="text">5 stars</label>
                                          <input type="radio" id="star4" name="rate" value="4" />
                                          <label for="star4" title="text">4 stars</label>
                                          <input type="radio" id="star3" name="rate" value="3" />
                                          <label for="star3" title="text">3 stars</label>
                                          <input type="radio" id="star2" name="rate" value="2" />
                                          <label for="star2" title="text">2 stars</label>
                                          <input type="radio" id="star1" name="rate" value="1" />
                                          <label for="star1" title="text">1 star</label>
                                        </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button style="margin-top: 1rem;" class="btn btn-primary">Enviar</button>
                        </div>
                        <div class="card-footer text-muted text-center">
                           AG STUDIO 2023
                        </div>
                  </div>
                  </form>
               </div>
            </div>
         </div>
         </div>
      </main>
      <footer>
         <!-- Rodapé do site -->
      </footer>
   </body>
</html>